---
language: go

go:
  - 1.13.x
  
before_install:
before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - go get github.com/corsc/go-tools/package-coverage
  
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - find ./* -name "profile.cov" -type f -exec sh -c 'gocov convert {} | gocov-xml > {}.xml' \;
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -f "*.cov.xml"